blueprint:
  name: Rollo-Steuerung (v10)
  description: >
    Schließt Rollos nach Dämmerung + Offset. 
    Interrupt-sicher: Fensterbewegungen unterbrechen das Warten nicht permanent.
  domain: automation
  input:
    target_cover:
      name: Rollo
      selector:
        entity:
          domain: cover
    window_sensor:
      name: Fenster- oder Türsensor
      selector:
        entity:
          domain: binary_sensor
          device_class: [window, door]
    #sunset_offset_mins:
    #  name: Verzögerung (Minuten)
    #  default: 30
    #  selector:
    #    number:
    #      min: -120
    #      max: 300
    #      unit_of_measurement: min
    #      mode: box
    sunset_close_trigger_helper:
      name: Helfervariable für das Schließen des Rollos
      selector:
        entity:
          domain: binary_sensor
    notify_device:
      name: Benachrichtigungs-Dienst (Optional)
      default: []
      selector:
        action: {}
    enable_auto_open:
      name: Automatisch öffnen
      default: false
      selector:
        boolean: {}
    open_position_pct:
      name: Öffnungsgrad
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

variables:
  target_cover_entity: !input target_cover
  #offset_mins: !input sunset_offset_mins
  # Berechnet den Zielzeitpunkt absolut (heutige Dämmerung + Offset)
  #target_time: >
  #  {% set next_dusk = states('sensor.sun_next_dusk') | as_datetime %}
  #  {% set dusk = next_dusk - timedelta(days=1) if next_dusk > now() + timedelta(hours=12) else next_dusk %}
  #  {{ dusk + timedelta(minutes=offset_mins | int) }}

mode: restart

trigger:
  #- platform: time
  #  at: sensor.sun_next_dusk
  #  id: "zeit_event"
  - platform: state
    entity_id: !input sunset_close_trigger_helper
    to: "on" # Reagiert spezifisch auf das Aktivieren
    id: "zeit_event"
  - platform: state
    entity_id: !input window_sensor
    id: "sensor_event"

action:
  - choose:
      # FALL 1: FENSTER WIRD GEÖFFNET (Rollo hochfahren)
      - conditions:
          - condition: trigger
            id: "sensor_event"
        sequence:
          - if:
              - condition: state
                entity_id: !input window_sensor
                state: "on"
              - condition: template
                value_template: !input enable_auto_open
              - condition: state
                entity_id: !input sunset_close_trigger_helper
                state: "on"
              #- condition: template
              #  value_template: "{{ now() >= target_time | as_datetime }}"
            then:
              - service: cover.set_cover_position
                target:
                  entity_id: !input target_cover
                data:
                  position: !input open_position_pct

      # FALL 2: SCHLIESS-LOGIK
      - conditions:
          - condition: trigger
            id: "zeit_event"
          #- condition: template
          #  value_template: "{{ now() >= (target_time | as_datetime - timedelta(minutes=1)) }}"
        sequence:
          #- wait_template: "{{ now() >= target_time | as_datetime }}"
          # A: Falls Fenster offen -> Benachrichtigen
          - if:
              - condition: state
                entity_id: !input window_sensor
                state: "on"
            then:
              - choose: []
                default: !input notify_device
          
          # B: Nur schließen, wenn Fenster ZU ist
          # Dank 'mode: restart' wird dieser Teil sofort ausgeführt, 
          # sobald das Fenster während der "An-Phase" geschlossen wird.
          - if:
              - condition: state
                entity_id: !input window_sensor
                state: "off"
              # Optional: Nur schließen, wenn es nicht schon zu ist
              - condition: template
                value_template: "{{ state_attr(target_cover_entity, 'current_position') | int > 0 }}"
            then:
              - service: cover.close_cover
                target:
                  entity_id: !input target_cover