blueprint:
  name: Rollo-Steuerung (Smarte Fensteröffnung - Fix)
  description: >
    Schließt das Rollo X Minuten nach Sonnenuntergang (Fenster-Check).
    Öffnet das Rollo optional auf eine Wunschposition beim Öffnen (nur nach Sonnenuntergang).
  domain: automation
  input:
    target_cover:
      name: Rollo (Cover)
      selector:
        entity:
          domain: cover
    window_sensor:
      name: Fenster- oder Türsensor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
    sunset_offset_mins:
      name: Verzögerung nach Sonnenuntergang (Minuten)
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: min
          mode: box
    enable_auto_open:
      name: Automatisch öffnen bei Öffnung
      default: false
      selector:
        boolean: {}
    open_position_pct:
      name: Öffnungsgrad bei Öffnung
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

mode: restart

variables:
  offset_mins: !input sunset_offset_mins
  open_position: !input open_position_pct

trigger:
  # Auslöser 1: Direkt zum Sonnenuntergang
  - platform: sun
    event: sunset
    offset: "00:00:00"
    id: "sonnenuntergang_event"
  
  # Auslöser 2: Fenster/Tür wird geschlossen
  - platform: state
    entity_id: !input window_sensor
    from: "on"
    to: "off"
    id: "sensor_wurde_zu"
  
  # Auslöser 3: Fenster/Tür wird geöffnet
  - platform: state
    entity_id: !input window_sensor
    from: "off"
    to: "on"
    id: "sensor_wurde_auf"

action:
  - choose:
      # FALL 1: SENSOR WIRD GEÖFFNET
      - conditions:
          - condition: trigger
            id: "sensor_wurde_auf"
          - condition: template
            value_template: !input enable_auto_open
          # Prüfung: Ist es bereits nach Sonnenuntergang + Offset?
          - condition: template
            value_template: >
              {% set sunset = as_datetime(state_attr('sun.sun', 'next_setting')) %}
              {% if sunset > now() + timedelta(hours=12) %}
                {% set sunset = sunset - timedelta(days=1) %}
              {% endif %}
              {{ now() >= sunset + timedelta(minutes=offset_mins | int) }}
        sequence:
          - service: cover.set_cover_position
            target:
              entity_id: !input target_cover
            data:
              position: "{{ open_position }}"

      # FALL 2: SONNENUNTERGANG ERREICHT
      - conditions:
          - condition: trigger
            id: "sonnenuntergang_event"
        sequence:
          # Warte die eingestellten Minuten
          - delay:
              minutes: "{{ offset_mins | int }}"
          # Prüfe ob Fenster zu ist
          - condition: state
            entity_id: !input window_sensor
            state: "off"
          - service: cover.close_cover
            target:
              entity_id: !input target_cover

      # FALL 3: SENSOR WIRD NACH DER ZEIT GESCHLOSSEN
      - conditions:
          - condition: trigger
            id: "sensor_wurde_zu"
          # Prüfung: Ist es bereits nach Sonnenuntergang + Offset?
          - condition: template
            value_template: >
              {% set sunset = as_datetime(state_attr('sun.sun', 'next_setting')) %}
              {% if sunset > now() + timedelta(hours=12) %}
                {% set sunset = sunset - timedelta(days=1) %}
              {% endif %}
              {{ now() >= sunset + timedelta(minutes=offset_mins | int) }}
        sequence:
          - service: cover.close_cover
            target:
              entity_id: !input target_cover