blueprint:
  name: Rollo-Steuerung (Smarte Fensteröffnung nach Sonnenuntergang)
  description: >
    1. Schließt das Rollo X Minuten nach Sonnenuntergang, falls das Fenster zu ist.
    2. Schließt das Rollo, wenn das Fenster nach der Zeit geschlossen wird.
    3. Öffnet das Rollo auf eine bestimmte Prozentzahl, wenn das Fenster geöffnet wird,
       ABER NUR wenn es bereits nach Sonnenuntergang (+ Offset) ist.
  domain: automation
  input:
    target_cover:
      name: Rollo (Cover)
      description: Das Rollo, das gesteuert werden soll.
      selector:
        entity:
          domain: cover
    window_sensor:
      name: Fenstersensor
      description: Der Sensor für das Fenster.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
    sunset_offset_mins:
      name: Verzögerung nach Sonnenuntergang (Minuten)
      description: Minuten, die nach Sonnenuntergang gewartet werden soll.
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: min
          mode: box
    enable_auto_open:
      name: Automatisch öffnen bei Fensteröffnung
      description: Wenn aktiviert, fährt das Rollo hoch, sobald das Fenster geöffnet wird (nur nach Sonnenuntergang).
      default: false
      selector:
        boolean: {}
    open_position_pct:
      name: Öffnungsgrad bei Fensteröffnung
      description: Auf wie viel Prozent soll das Rollo fahren? (100 = ganz offen)
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

mode: restart

variables:
  offset_mins: !input sunset_offset_mins
  open_position: !input open_position_pct

trigger:
  # Auslöser 1: Zeit erreicht (Sonnenuntergang + X Minuten)
  #- platform: template
  #  value_template: >
  #    {% set sunset = as_datetime(state_attr('sun.sun', 'next_setting')) %}
  #    {% if sunset > now() %}
  #      {% set sunset = sunset - timedelta(days=1) %}
  #    {% endif %}
  #    {{ now() >= sunset + timedelta(minutes=offset_mins | int) }}
  #  id: "zeit_zum_schliessen"

  - trigger: time
    at: input_datetime.next_sunset_with_offset

  # Auslöser 2: Fenster wird geschlossen
  - platform: state
    entity_id: !input window_sensor
    from: "on"
    to: "off"
    id: "fenster_wurde_zu"

  # Auslöser 3: Fenster wird geöffnet
  - platform: state
    entity_id: !input window_sensor
    from: "off"
    to: "on"
    id: "fenster_wurde_auf"

action:
  - choose:
      # FALL 1: Fenster wird geöffnet
      - conditions:
          - condition: trigger
            id: "fenster_wurde_auf"
          # Checkbox muss aktiv sein
          - condition: template
            value_template: !input enable_auto_open
          # NEU: Es muss bereits NACH der Sonnenuntergangszeit (+ Offset) sein
          - condition: template
            value_template: >
              {% set sunset = as_datetime(state_attr('sun.sun', 'next_setting')) %}
              {% if sunset > now() %}
                {% set sunset = sunset - timedelta(days=1) %}
              {% endif %}
              {{ now() >= sunset + timedelta(minutes=offset_mins | int) }}
        sequence:
          - service: cover.set_cover_position
            target:
              entity_id: !input target_cover
            data:
              position: "{{ open_position }}"

      # FALL 2: Schließen-Logik (Zeit erreicht oder Fenster wird nach der Zeit geschlossen)
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "zeit_zum_schliessen"
              - condition: trigger
                id: "fenster_wurde_zu"
          - condition: state
            entity_id: !input window_sensor
            state: "off"
          - condition: time
            after: input_datetime.next_sunset_with_offset
        sequence:
          - service: cover.close_cover
            target:
              entity_id: !input target_cover
