blueprint:
  name: Rollo-Steuerung (Smarte Fensteröffnung) - (v5)
  description: >
    Schließt das Rollo X Minuten nach der Dämmerung (sun_next_dusk).
    Verhindert das Aussperren und ermöglicht automatisches Öffnen.
  domain: automation
  input:
    target_cover:
      name: Rollo (Cover)
      selector:
        entity:
          domain: cover
    window_sensor:
      name: Fenster- oder Türsensor
      selector:
        entity:
          domain: binary_sensor
          device_class: [window, door]
    sunset_offset_mins:
      name: Verzögerung nach Dämmerung (Minuten)
      default: 30
      selector:
        number:
          min: -120
          max: 300
          unit_of_measurement: min
          mode: box
    enable_auto_open:
      name: Automatisch öffnen bei Öffnung
      default: false
      selector:
        boolean: {}
    open_position_pct:
      name: Öffnungsgrad bei Öffnung
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

mode: restart

variables:
  offset_mins: !input sunset_offset_mins
  open_pos: !input open_position_pct
  # Hilfs-Variable zur Berechnung der "echten" heutigen Dämmerung
  dusk_time: >
    {% set next_dusk = states('sensor.sun_next_dusk') | as_datetime %}
    {# Wenn dusk mehr als 12h in der Zukunft liegt, ist der Sensor bereits auf morgen gesprungen #}
    {% if next_dusk > now() + timedelta(hours=12) %}
      {% set dusk = next_dusk - timedelta(days=1) %}
    {% else %}
      {% set dusk = next_dusk %}
    {% endif %}
    {{ dusk + timedelta(minutes=offset_mins | int) }}

trigger:
  # Auslöser 1: Zeitpunkt erreicht (Dämmerung + Offset)
  - platform: template
    value_template: "{{ now() >= dusk_time | as_datetime }}"
    id: "zeit_event"
  
  # Auslöser 2: Fenster wird geschlossen
  - platform: state
    entity_id: !input window_sensor
    from: "on"
    to: "off"
    id: "sensor_wurde_zu"
  
  # Auslöser 3: Fenster wird geöffnet
  - platform: state
    entity_id: !input window_sensor
    from: "off"
    to: "on"
    id: "sensor_wurde_auf"

action:
  - choose:
      # FALL 1: SENSOR WIRD GEÖFFNET
      - conditions:
          - condition: trigger
            id: "sensor_wurde_auf"
          - condition: template
            value_template: !input enable_auto_open
          # Nur öffnen, wenn es bereits "Dämmerungs-Zeit" ist
          - condition: template
            value_template: "{{ now() >= dusk_time | as_datetime }}"
        sequence:
          - service: cover.set_cover_position
            target:
              entity_id: !input target_cover
            data:
              position: "{{ open_pos }}"

      # FALL 2: ZEIT ERREICHT ODER NACHTRÄGLICH GESCHLOSSEN
      - conditions:
          - or:
              - condition: trigger
                id: "zeit_event"
              - condition: trigger
                id: "sensor_wurde_zu"
          # Bedingung: Es muss nach der Dämmerungs-Zeit sein
          - condition: template
            value_template: "{{ now() >= dusk_time | as_datetime }}"
          # Bedingung: Fenster muss zu sein
          - condition: state
            entity_id: !input window_sensor
            state: "off"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: !input target_cover