blueprint:
  name: "Präsenz-Heizungssteuerung (Comfort vs. Auto-Modus)"
  description: "Setzt Wohlfühltemperatur bei Präsenz und wechselt in den 'Auto'-Modus bei Abwesenheit, offenem Fenster oder außerhalb der Zeit."
  domain: automation
  input:
    climate_entity:
      name: Thermostat
      selector:
        entity:
          domain: climate
    window_sensor:
      name: Fenster-/Tür-Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    presence_sensor:
      name: Anwesenheitssensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    outdoor_temp_sensor:
      name: Außentemperatur-Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    outdoor_temp_threshold:
      name: Außentemperatur-Schwellenwert
      default: 15
      selector:
        number:
          min: -10
          max: 25
          step: 0.5
          unit_of_measurement: °C
    start_time:
      name: Start-Uhrzeit
      default: "08:00:00"
      selector:
        time: {}
    end_time:
      name: End-Uhrzeit
      default: "18:00:00"
      selector:
        time: {}
    presence_delay:
      name: Dauer nach Anwesenheit (Minuten)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: min
    absence_delay:
      name: Dauer nach Abwesenheit (Minuten)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: min
    comfort_temp:
      name: Wohlfühltemperatur
      default: 21
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
          unit_of_measurement: °C

mode: restart

trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: state
    entity_id: !input window_sensor
  - platform: state
    entity_id: !input outdoor_temp_sensor
  - platform: time
    at: !input end_time
  - platform: time
    at: !input start_time

action:
  - choose:
      # FALL 1: Wohlfühltemperatur (Heizen)
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
          - condition: state
            entity_id: !input window_sensor
            state: "off"
          - condition: time
            after: !input start_time
            before: !input end_time
          - condition: numeric_state
            entity_id: !input outdoor_temp_sensor
            below: !input outdoor_temp_threshold
        sequence:
          - delay:
              minutes: !input presence_delay
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
          # Wir setzen hier explizit die Temperatur (das schaltet viele Thermostate autom. in 'heat')
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input comfort_temp

      # FALL 2: Zurück in den Auto-Modus (Sparen)
      - conditions:
          - or:
              - condition: state
                entity_id: !input presence_sensor
                state: "off"
              - condition: state
                entity_id: !input window_sensor
                state: "on"
              - condition: time
                after: !input end_time
              - condition: time
                before: !input start_time
              - condition: numeric_state
                entity_id: !input outdoor_temp_sensor
                above: !input outdoor_temp_threshold
        sequence:
          - if:
              - condition: state
                entity_id: !input presence_sensor
                state: "off"
            then:
              - delay:
                  minutes: !input absence_delay
              - condition: state
                entity_id: !input presence_sensor
                state: "off"
          # Wechsel in den HVAC-Modus "auto"
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: "auto"