blueprint:
  name: "Präsenz-Heizungssteuerung (v14)"
  description: "Heizt bei Anwesenheit im Zeitfenster und schaltet auf 'auto' zurück. Startet nur durch Ereignisse (Bewegung/Fenster), nicht hart zum Zeitstart."
  domain: automation
  input:
    climate_entity:
      name: Thermostat
      selector:
        entity:
          domain: climate
    window_sensor:
      name: Fenster-/Tür-Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
    presence_sensor:
      name: Anwesenheitssensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    outdoor_temp_sensor:
      name: Außentemperatur-Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    outdoor_temp_threshold:
      name: Außentemperatur-Schwellenwert
      default: 15
      selector:
        number:
          min: -10
          max: 25
          step: 0.5
          unit_of_measurement: °C
    start_time:
      name: Start-Uhrzeit
      default: "08:00:00"
      selector:
        time: {}
    end_time:
      name: End-Uhrzeit
      default: "18:00:00"
      selector:
        time: {}
    presence_delay:
      name: Dauer nach Anwesenheit (Minuten)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: min
    absence_delay:
      name: Dauer nach Abwesenheit (Minuten)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: min
    comfort_temp:
      name: Wohlfühltemperatur
      default: 21
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
          unit_of_measurement: °C
    min_delay:
      name: Mindestabstand zwischen zwei Ausführungen
      default: 5
      selector:
        number:
          min: 5
          max: 25
          step: 1
          unit_of_measurement: min
    last_finished_timestamp:
      name: Helfer-Variable für das Speichern des letzten vollständigen Durchlaufes
      selector:
        entity:
          domain: input_datetime

mode: restart

variables:
  presence_delay_val: !input presence_delay
  absence_delay_val: !input absence_delay
  min_delay_val: !input min_delay
  last_finished_timestamp_val: !input last_finished_timestamp
  climate_entity_state: !input climate_entity

trigger:
  - platform: state
    entity_id: !input presence_sensor
    id: "presence_sensor"
  - platform: state
    entity_id: !input window_sensor
    id: "window_sensor"
  - platform: time
    at: !input end_time
    id: "end_time"

action:
  # Ratenbegrenzung
  - or:
    - condition: template
      value_template: >
        {{ states(last_finished_timestamp_val) == None or 
          (now() - states(last_finished_timestamp_val) | as_datetime | as_local).total_seconds() >= (min_delay_val * 60) }}
    - condition: trigger
      id: "end_time"
  - condition: template
    value_template: "{{ states(climate_entity_state) != 'off' }}"
  
  - choose:
      # FALL 1: Heizzeit abgelaufen, zurück in Auto-Modus (sparen)
      - conditions:
          - condition: trigger
            id: "end_time"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: "auto"

      # FALL 2: Wohlfühltemperatur (Heizen)
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
          - condition: state
            entity_id: !input window_sensor
            state: "off"
          - condition: time
            after: !input start_time
            before: !input end_time
          - condition: numeric_state
            entity_id: !input outdoor_temp_sensor
            below: !input outdoor_temp_threshold
        sequence:
          - delay:
              minutes: !input presence_delay
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input comfort_temp
          - service: input_datetime.set_datetime
            target:
              entity_id: !input last_finished_timestamp
            data:
              datetime: "{{ now() }}"

      # FALL 3: Zurück in den Auto-Modus (sparen)
      - conditions:
          - or:
              - condition: state
                entity_id: !input presence_sensor
                state: "off"
              - condition: state
                entity_id: !input window_sensor
                state: "on"
              - condition: numeric_state
                entity_id: !input outdoor_temp_sensor
                above: !input outdoor_temp_threshold
        sequence:
          - if:
              - condition: time
                after: !input start_time
              - condition: time
                before: !input end_time
            then:
              - if:
                  - condition: state
                    entity_id: !input presence_sensor
                    state: "off"
                then:
                  - delay:
                      minutes: !input absence_delay
                  - condition: state
                    entity_id: !input presence_sensor
                    state: "off"
              - service: climate.set_hvac_mode
                target:
                  entity_id: !input climate_entity
                data:
                  hvac_mode: "auto"
              - service: input_datetime.set_datetime
                target:
                  entity_id: !input last_finished_timestamp
                data:
                  datetime: "{{ now() }}"
                  