blueprint:
  name: "Präsenz-Heizungssteuerung mit Außentemperatur-Sperre (v3)"
  description: "Heizt nur bei Anwesenheit, geschlossenem Fenster, im Zeitfenster UND wenn es draußen kalt genug ist."
  domain: automation
  input:
    climate_entity:
      name: Thermostat
      selector:
        entity:
          domain: climate
    window_sensor:
      name: Fenster- oder Türsensor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
    presence_sensor:
      name: Anwesenheitssensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    outdoor_temp_sensor:
      name: Außentemperatur-Sensor
      description: Die Entität, die die aktuelle Außentemperatur liefert.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    outdoor_temp_threshold:
      name: Außentemperatur-Schwellenwert
      description: Wohlfühltemperatur wird nur aktiviert, wenn es draußen kälter als dieser Wert ist.
      default: 15
      selector:
        number:
          min: -10
          max: 25
          step: 0.5
          unit_of_measurement: °C
    start_time:
      name: Start-Uhrzeit
      default: "08:00:00"
      selector:
        time: {}
    end_time:
      name: End-Uhrzeit
      default: "18:00:00"
      selector:
        time: {}
    presence_delay:
      name: Dauer nach Anwesenheit (Minuten)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: min
    absence_delay:
      name: Dauer nach Abwesenheit (Minuten)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: min
    comfort_temp:
      name: Wohlfühltemperatur
      default: 21
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
          unit_of_measurement: °C
    eco_temp:
      name: Eco-Temperatur
      default: 17
      selector:
        number:
          min: 5
          max: 20
          step: 0.5
          unit_of_measurement: °C

mode: restart

trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: state
    entity_id: !input window_sensor
  - platform: state
    entity_id: !input outdoor_temp_sensor
  - platform: time
    at: !input end_time
  - platform: time
    at: !input start_time

action:
  - choose:
      # FALL 1: Heizen (Wohlfühltemperatur)
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
          - condition: state
            entity_id: !input window_sensor
            state: "off"
          - condition: time
            after: !input start_time
            before: !input end_time
          - condition: numeric_state
            entity_id: !input outdoor_temp_sensor
            below: !input outdoor_temp_threshold
        sequence:
          - delay:
              minutes: !input presence_delay
          # Sicherheitsprüfung nach Delay
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input comfort_temp

      # FALL 2: Sparen (Eco-Temperatur)
      - conditions:
          - or:
              - condition: state
                entity_id: !input presence_sensor
                state: "off"
              - condition: state
                entity_id: !input window_sensor
                state: "on"
              - condition: time
                after: !input end_time
              - condition: time
                before: !input start_time
              - condition: numeric_state
                entity_id: !input outdoor_temp_sensor
                above: !input outdoor_temp_threshold
        sequence:
          - if:
              - condition: state
                entity_id: !input presence_sensor
                state: "off"
            then:
              - delay:
                  minutes: !input absence_delay
              # Sicherheitsprüfung: Nur umschalten, wenn immer noch niemand da ist
              - condition: state
                entity_id: !input presence_sensor
                state: "off"
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input eco_temp